import { NextRequest } from 'next/server'

const g = global as any

// Consume a one-time tap token generated by /api/uid.
// Returns { valid: true, uid, ctr } on first call; { valid: false } on replay / expiry.
export function GET(req: NextRequest) {
  const tapId   = req.nextUrl.searchParams.get('tapId') ?? ''
  if (!tapId) return Response.json({ valid: false })

  const tapSess = g.__tapSess as Map<string, { uid: string; ctr: number | null; expiresAt: number }> | undefined
  if (!tapSess)  return Response.json({ valid: false })

  const session = tapSess.get(tapId)
  if (!session || session.expiresAt < Date.now()) {
    if (session) tapSess.delete(tapId)
    return Response.json({ valid: false })
  }

  return Response.json({ valid: true, uid: session.uid, ctr: session.ctr })
}
